'use strict';
const ids=['x1','y1','x2','y2','x'];
const el=id=>document.getElementById(id);
const fmt=n=>Number(n.toPrecision(12)).toLocaleString('es-PE',{maximumSignificantDigits:12,useGrouping:false});
function parse(text){const s=String(text).trim().replace(',','.');if(!/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(s))throw Error('Completa todos los campos con números válidos.');const n=Number(s);if(!Number.isFinite(n)||Math.abs(n)>1e100||(n!==0&&Math.abs(n)<1e-100)||(n===0&&/[1-9]/.test(s.split(/e/i)[0])))throw Error('Usa números entre 1e−100 y 1e100 en valor absoluto, o cero.');return n;}
function solve(d){if(d.x1===d.x2)throw Error('x₁ y x₂ deben ser distintos. No se puede dividir entre cero.');const t=(d.x-d.x1)/(d.x2-d.x1),y=d.y1+t*(d.y2-d.y1);if(!Number.isFinite(y))throw Error('El resultado supera el rango de cálculo. Usa valores de menor magnitud.');return {...d,t,y,outside:d.x<Math.min(d.x1,d.x2)||d.x>Math.max(d.x1,d.x2)};}
function graph(r){const svg=el('chart');svg.replaceChildren();const add=(tag,attrs,text)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n;};const xs=[r.x1,r.x2,r.x],ys=[r.y1,r.y2,r.y],xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),dx=xmax-xmin,dy=ymax-ymin||Math.max(1,Math.abs(ymin)*.2);const X=x=>90+(x-xmin)/dx*505,Y=y=>265-(y-ymin)/dy*210;
for(let i=0;i<=4;i++){const x=xmin+dx*i/4,y=ymin+dy*i/4;add('line',{x1:90,y1:Y(y),x2:610,y2:Y(y),stroke:'#e8eef5'});add('line',{x1:X(x),y1:40,x2:X(x),y2:265,stroke:'#e8eef5'});add('text',{x:80,y:Y(y)+4,'text-anchor':'end',fill:'#718197','font-size':12},fmt(y));add('text',{x:X(x),y:290,'text-anchor':'middle',fill:'#718197','font-size':12},fmt(x));}
add('text',{x:625,y:289,fill:'#52657d','font-size':14},'x');add('text',{x:75,y:23,fill:'#52657d','font-size':14},'y');
const line=(a,b,attrs={})=>add('line',{x1:X(a[0]),y1:Y(a[1]),x2:X(b[0]),y2:Y(b[1]),stroke:'#426aa5','stroke-width':3,...attrs});
if(r.outside){const p=Math.abs(r.x-r.x1)<Math.abs(r.x-r.x2)?[r.x1,r.y1]:[r.x2,r.y2];line(p,[r.x,r.y],{'stroke-dasharray':'7 6'});}
line([r.x1,r.y1],[r.x2,r.y2]);add('line',{x1:X(r.x),y1:Y(r.y),x2:X(r.x),y2:265,stroke:'#168c72','stroke-dasharray':'4 5'});[[r.x1,r.y1],[r.x2,r.y2]].forEach(p=>add('circle',{cx:X(p[0]),cy:Y(p[1]),r:6,fill:'#426aa5',stroke:'white','stroke-width':3}));add('circle',{cx:X(r.x),cy:Y(r.y),r:8,fill:'#168c72',stroke:'white','stroke-width':3});svg.setAttribute('aria-label',`Puntos (${fmt(r.x1)}, ${fmt(r.y1)}) y (${fmt(r.x2)}, ${fmt(r.y2)}). Resultado (${fmt(r.x)}, ${fmt(r.y)}).`);}
function resetOutput(message){el('value').textContent='y = —';el('kind').textContent='RESULTADO';el('caption').textContent=message;el('chart').replaceChildren();el('chart').setAttribute('aria-label','Sin resultado calculado');el('steps').replaceChildren();el('graphNote').textContent='Calcula un resultado para ver la recta.';}
function calculate(){el('error').hidden=true;ids.forEach(id=>el(id).removeAttribute('aria-invalid'));try{const d={};for(const id of ids){try{d[id]=parse(el(id).value);}catch(e){el(id).setAttribute('aria-invalid','true');throw e;}}const r=solve(d);el('kind').textContent=r.outside?'RESULTADO · EXTRAPOLACIÓN':'RESULTADO · INTERPOLACIÓN';el('value').textContent='y ≈ '+fmt(r.y);el('caption').textContent=r.outside?`Para x = ${fmt(r.x)}. Aviso: está fuera del intervalo conocido.`:`Para x = ${fmt(r.x)}, dentro del intervalo conocido.`;el('graphNote').textContent=r.outside?'La línea discontinua prolonga la recta fuera del intervalo.':'La recta conecta los dos puntos conocidos.';const items=[['Sustituir los datos',`y = (${fmt(r.y1)}) + [(${fmt(r.x)} − (${fmt(r.x1)})) / (${fmt(r.x2)} − (${fmt(r.x1)}))] × (${fmt(r.y2)} − (${fmt(r.y1)}))`],['Calcular la proporción',`(x − x₁) / (x₂ − x₁) ≈ ${fmt(r.t)}`],['Obtener el resultado',`y ≈ ${fmt(r.y)}`]];el('steps').replaceChildren(...items.map(([title,text])=>{const li=document.createElement('li'),strong=document.createElement('strong');strong.textContent=title;li.append(strong,document.createTextNode(text));return li;}));graph(r);return r;}catch(e){resetOutput('Revisa los datos e inténtalo de nuevo.');el('error').textContent=e.message;el('error').hidden=false;return {error:e.message};}}
el('form').addEventListener('submit',e=>{e.preventDefault();calculate();});el('example').addEventListener('click',()=>{[10,100,20,200,15].forEach((v,i)=>el(ids[i]).value=v);calculate();});el('clear').addEventListener('click',()=>{ids.forEach(id=>{el(id).value='';el(id).removeAttribute('aria-invalid');});el('error').hidden=true;resetOutput('Ingresa tus puntos para comenzar.');el('x1').focus();});ids.forEach(id=>el(id).addEventListener('input',()=>{resetOutput('Datos modificados. Pulsa Calcular interpolación.');el('error').hidden=true;}));calculate();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'calcular_interpolacion',description:'Ingresa dos puntos y un valor x, calcula y muestra el resultado, procedimiento y gráfico.',inputSchema:{type:'object',properties:Object.fromEntries(ids.map(id=>[id,{type:'number'}])),required:ids,additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const d={};for(const id of ids){if(typeof input?.[id]!=='number')throw Error('Se requieren cinco números.');d[id]=parse(input[id]);}solve(d);ids.forEach(id=>el(id).value=String(d[id]));return calculate();}})).catch(()=>{});}catch{}}
