/* Contrastes y selección muestral. Depende del núcleo estadistica.js. */
(function(root){'use strict';
const S=typeof module!=='undefined'?require('./estadistica.js'):root.Stats;
function gammaP(a,x){if(x<=0)return 0;const factor=Math.exp(-x+a*Math.log(x)-S.lgamma(a));if(x<a+1){let sum=1/a,term=sum;for(let i=1;i<30000;i++){term*=x/(a+i);sum+=term;if(Math.abs(term)<Math.abs(sum)*1e-14)return Math.min(1,sum*factor);}}else{let b=x+1-a,c=1e300,d=1/b,h=d;for(let i=1;i<30000;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const dt=d*c;h*=dt;if(Math.abs(dt-1)<1e-14)return Math.max(0,1-factor*h);}}throw Error('No convergió la distribución. Revisa tus datos.');}
function cdf(x,type,d1,d2){if(x<=0)return 0;return type==='chi'?gammaP(d1/2,x/2):S.beta(d1*x/(d1*x+d2),d1/2,d2/2);}
function quant(p,type,d1,d2){let lo=0,hi=Math.max(1,d1);while(cdf(hi,type,d1,d2)<p&&hi<1e14)hi*=2;for(let i=0;i<140;i++){const mid=(lo+hi)/2;if(cdf(mid,type,d1,d2)<p)lo=mid;else hi=mid;}return (lo+hi)/2;}
function pdf(x,type,d1,d2){if(x<=0)return 0;if(type==='chi')return Math.exp((d1/2-1)*Math.log(x)-x/2-d1/2*Math.log(2)-S.lgamma(d1/2));const a=d1/2,b=d2/2;return Math.exp(a*Math.log(d1/d2)+(a-1)*Math.log(x)-(a+b)*Math.log1p(d1*x/d2)-S.lgamma(a)-S.lgamma(b)+S.lgamma(a+b));}
function tailCheck(t){if(!['two','left','right'].includes(t))throw Error('Alternativa inválida.');}
function variance(d){tailCheck(d.tail);const alpha=S.level(d.confidence);S.count(d.n1,'n₁',2);if(d.n1>100000)throw Error('n₁ no debe superar 100 000.');S.positive(d.s1,'s₁');let statistic,d1=d.n1-1,d2=null,type=d.type;if(type==='chi'){S.positive(d.v0,'Varianza hipotética σ₀²');statistic=d1*d.s1*d.s1/d.v0;}else if(type==='f'){S.count(d.n2,'n₂',2);if(d.n2>100000)throw Error('n₂ no debe superar 100 000.');S.positive(d.s2,'s₂');d2=d.n2-1;statistic=d.s1*d.s1/(d.s2*d.s2);}else throw Error('Método desconocido.');if(!Number.isFinite(statistic)||statistic<=0)throw Error('Resultado fuera del rango numérico.');const left=cdf(statistic,type,d1,d2),p=d.tail==='two'?2*Math.min(left,1-left):d.tail==='left'?left:1-left,low=d.tail==='right'?0:quant(d.tail==='two'?alpha/2:alpha,type,d1,d2),high=d.tail==='left'?Infinity:quant(d.tail==='two'?1-alpha/2:1-alpha,type,d1,d2);const estimate=type==='chi'?d.s1*d.s1:statistic;const ci=type==='chi'?[d1*estimate/quant(1-alpha/2,type,d1),d1*estimate/quant(alpha/2,type,d1)]:[estimate/quant(1-alpha/2,type,d1,d2),estimate/quant(alpha/2,type,d1,d2)];return {...d,alpha,statistic,d1,d2,p:Math.max(0,Math.min(1,p)),low,high,ci,reject:p<=alpha};}
function compare(d){tailCheck(d.tail);const alpha=S.level(d.confidence);S.valid(d.delta,'Diferencia hipotética');let estimate,se,df,n1,n2,sd1,sd2,mean1,mean2;if(d.type==='paired'){if(d.a.length!==d.b.length)throw Error('Las listas relacionadas deben tener la misma cantidad de observaciones.');const dif=S.summary(d.a.map((v,i)=>v-d.b[i]));S.positive(dif.sd,'Desviación de las diferencias');estimate=dif.mean;se=dif.sd/Math.sqrt(dif.n);df=dif.n-1;n1=n2=dif.n;sd1=dif.sd;mean1=S.summary(d.a).mean;mean2=S.summary(d.b).mean;}else{let a,b;if(d.raw){a=S.summary(d.a);b=S.summary(d.b);}else{a={mean:d.mean1,sd:d.s1,n:d.n1};b={mean:d.mean2,sd:d.s2,n:d.n2};}for(const [label,v]of [['1',a],['2',b]]){S.count(v.n,'n'+label,2);if(v.n>1e6)throw Error('n no debe superar 1 000 000.');S.positive(v.sd,'s'+label);S.valid(v.mean,'Media '+label);}mean1=a.mean;mean2=b.mean;n1=a.n;n2=b.n;sd1=a.sd;sd2=b.sd;estimate=a.mean-b.mean;const u=a.sd*a.sd/a.n,v=b.sd*b.sd/b.n;if(d.type==='pooled'){df=a.n+b.n-2;const pooled=((a.n-1)*a.sd*a.sd+(b.n-1)*b.sd*b.sd)/df;se=Math.sqrt(pooled*(1/a.n+1/b.n));}else if(d.type==='welch'){se=Math.sqrt(u+v);df=(u+v)**2/(u*u/(a.n-1)+v*v/(b.n-1));}else throw Error('Método desconocido.');}if(!Number.isFinite(se)||se<=0||!Number.isFinite(df)||df<=0)throw Error('Escala numérica no válida: revisa las desviaciones.');const statistic=(estimate-d.delta)/se,p=d.tail==='two'?2*S.sf(Math.abs(statistic),df):d.tail==='left'?S.sf(-statistic,df):S.sf(statistic,df),q=S.quantile(1-alpha/2,df);return {...d,alpha,estimate,se,df,n1,n2,sd1,sd2,mean1,mean2,statistic,p,reject:p<=alpha,critical:S.quantile(1-alpha/(d.tail==='two'?2:1),df),ci:[estimate-q*se,estimate+q*se]};}
function power(d){tailCheck(d.tail);const alpha=S.level(d.confidence);S.positive(d.sd,'σ conocida');S.valid(d.delta,'Efecto μ₁ − μ₀');S.count(d.n,'n',2);if(d.n>1e6)throw Error('n no debe superar 1 000 000.');S.probability(d.target,'Potencia objetivo');if(d.target<=alpha)throw Error('La potencia objetivo debe ser mayor que α.');const q=S.quantile(1-alpha/(d.tail==='two'?2:1));const at=n=>{const shift=d.delta*Math.sqrt(n)/d.sd;return d.tail==='two'?S.sf(q-shift)+S.sf(q+shift):d.tail==='right'?S.sf(q-shift):S.sf(q+shift);};const value=at(d.n);let required=null;if(d.delta!==0&&(d.tail==='two'||(d.tail==='right'&&d.delta>0)||(d.tail==='left'&&d.delta<0))){let lo=2,hi=2;while(at(hi)<d.target&&hi<1e6)hi=Math.min(1e6,hi*2);if(at(hi)>=d.target){while(lo<hi){const mid=Math.floor((lo+hi)/2);if(at(mid)>=d.target)hi=mid;else lo=mid+1;}required=lo;}}return {...d,alpha,q,value,beta:1-value,required,at};}
function rng(seed){let state=seed>>>0;return ()=>{state+=0x6D2B79F5;let t=state;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
function shufflePick(rows,n,random){const pool=rows.slice();for(let i=0;i<n;i++){const j=i+Math.floor(random()*(pool.length-i));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,n);}
function allocate(groups,n,neyman){let allocation=groups.map(()=>0),remaining=n,active=groups.map((_,i)=>i);while(remaining>0&&active.length){let weights=active.map(i=>groups[i].length*(neyman?groups[i].sd:1));if(weights.every(x=>x===0))weights=active.map(i=>groups[i].length);const sum=weights.reduce((a,b)=>a+b,0);const shares=active.map((i,j)=>({i,quota:remaining*weights[j]/sum,cap:groups[i].length-allocation[i]}));const saturated=shares.filter(x=>x.quota>=x.cap);if(saturated.length){for(const s of saturated){allocation[s.i]+=s.cap;remaining-=s.cap;}active=active.filter(i=>!saturated.some(s=>s.i===i));continue;}for(const s of shares){let k=Math.floor(s.quota);allocation[s.i]+=k;remaining-=k;}shares.sort((a,b)=>(b.quota%1)-(a.quota%1)||a.i-b.i);for(const s of shares){if(!remaining)break;if(allocation[s.i]<groups[s.i].length){allocation[s.i]++;remaining--;}}break;}return allocation;}
function sampling(d){if(!d.rows.length||d.rows.length>100000)throw Error('La base debe contener entre 1 y 100 000 registros.');S.count(d.n,'Tamaño n');if(d.n>d.rows.length)throw Error('n no puede superar el número de registros.');S.count(d.seed,'Semilla',0);if(d.seed>4294967295)throw Error('La semilla debe ser menor que 2³².');if(new Set(d.rows.map(r=>r.id)).size!==d.rows.length)throw Error('Los identificadores deben ser únicos.');const random=rng(d.seed),N=d.rows.length;let selected,allocation=[],k,start;if(d.method==='mas')selected=shufflePick(d.rows,d.n,random);else if(d.method==='systematic'){k=N/d.n;start=random()*k;selected=Array.from({length:d.n},(_,i)=>d.rows[Math.floor(start+i*k)]);}else if(d.method==='stratified'){const map=new Map();d.rows.forEach(r=>{if(!r.stratum)throw Error('Cada registro necesita un estrato.');if(!map.has(r.stratum))map.set(r.stratum,[]);map.get(r.stratum).push(r);});const groups=[...map.values()];if(d.allocation==='neyman')for(const g of groups){g.forEach(r=>S.valid(r.value,'Valor auxiliar para Neyman'));let mean=0,m2=0,k=0;for(const r of g){k++;const delta=r.value-mean;mean+=delta/k;m2+=delta*(r.value-mean);}g.sd=k>1?Math.sqrt(m2/(k-1)):0;}const sizes=allocate(groups,d.n,d.allocation==='neyman');selected=[];[...map.keys()].forEach((name,i)=>{selected.push(...shufflePick(groups[i],sizes[i],random));allocation.push({name,N:groups[i].length,n:sizes[i],sd:groups[i].sd});});}else throw Error('Método de muestreo desconocido.');return {selected,N,n:d.n,k,start,allocation};}
const api={gammaP,cdf,quant,pdf,variance,compare,power,sampling,allocate,rng};if(typeof module!=='undefined')module.exports=api;root.Advanced=api;
})(typeof globalThis!=='undefined'?globalThis:this);
