/* Núcleo numérico independiente de la interfaz. Sin servicios externos. */
(function(root){
'use strict';
function valid(x,name){if(!Number.isFinite(x)||Math.abs(x)>1e12)throw Error(name+': introduce un número finito de magnitud no mayor que 10¹².');return x;}
function positive(x,name){valid(x,name);if(x<=0)throw Error(name+' debe ser mayor que cero.');return x;}
function count(x,name,min=1){valid(x,name);if(!Number.isSafeInteger(x)||x<min)throw Error(name+' debe ser un entero mayor o igual que '+min+'.');return x;}
function probability(x,name){valid(x,name);if(x<=0||x>=1)throw Error(name+' debe estar entre 0 y 1, sin incluir los extremos.');return x;}
function lgamma(z){const p=[676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-lgamma(1-z);z--;let x=.99999999999980993;for(let i=0;i<p.length;i++)x+=p[i]/(z+i+1);const t=z+p.length-.5;return .9189385332046727+(z+.5)*Math.log(t)-t+Math.log(x);}
function betacf(a,b,x){const tiny=1e-300;let c=1,d=1-(a+b)*x/(a+1);if(Math.abs(d)<tiny)d=tiny;d=1/d;let h=d;for(let m=1;m<=300;m++){let aa=m*(b-m)*x/((a+2*m-1)*(a+2*m));d=1+aa*d;if(Math.abs(d)<tiny)d=tiny;c=1+aa/c;if(Math.abs(c)<tiny)c=tiny;d=1/d;h*=d*c;aa=-(a+m)*(a+b+m)*x/((a+2*m)*(a+2*m+1));d=1+aa*d;if(Math.abs(d)<tiny)d=tiny;c=1+aa/c;if(Math.abs(c)<tiny)c=tiny;d=1/d;const delta=d*c;h*=delta;if(Math.abs(delta-1)<3e-14)return h;}throw Error('El cálculo numérico no convergió. Revisa la magnitud de los datos.');}
function beta(x,a,b){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(lgamma(a+b)-lgamma(a)-lgamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betacf(a,b,x)/a:1-bt*betacf(b,a,1-x)/b;}
function normalSF(x){if(x<0)return 1-normalSF(-x);if(x===0)return .5;const v=x*x/2,a=.5;if(v>745)return 0;const factor=Math.exp(-v+a*Math.log(v)-lgamma(a));if(v<a+1){let sum=1/a,term=sum,ap=a;for(let i=0;i<300;i++){ap++;term*=v/ap;sum+=term;if(Math.abs(term)<Math.abs(sum)*1e-15)break;}return .5*(1-sum*factor);}let b=v+1-a,c=1e300,d=1/b,h=d;for(let i=1;i<300;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const delta=d*c;h*=delta;if(Math.abs(delta-1)<1e-15)break;}return .5*factor*h;}
function sf(x,df){if(!df)return normalSF(x);const b=.5*beta(df/(df+x*x),df/2,.5);return x>=0?b:1-b;}
function quantile(p,df){probability(p,'Probabilidad');if(p===.5)return 0;if(p<.5)return -quantile(1-p,df);let lo=0,hi=1;while(sf(hi,df)>1-p&&hi<1e10)hi*=2;for(let i=0;i<100;i++){let mid=(lo+hi)/2;if(sf(mid,df)>1-p)lo=mid;else hi=mid;}return (lo+hi)/2;}
function density(x,df){return df?Math.exp(lgamma((df+1)/2)-lgamma(df/2)-.5*Math.log(df*Math.PI)-(df+1)/2*Math.log1p(x*x/df)):Math.exp(-x*x/2)/Math.sqrt(2*Math.PI);}
function summary(values){if(values.length<2||values.length>10000)throw Error('Ingresa entre 2 y 10 000 observaciones.');let mean=0,m2=0,n=0;for(const x of values){valid(x,'Observación');n++;const delta=x-mean;mean+=delta/n;m2+=delta*(x-mean);}return {n,mean,sd:Math.sqrt(m2/(n-1))};}
function level(c){if(![.90,.95,.99].includes(c))throw Error('Selecciona 90 %, 95 % o 99 % de confianza.');return 1-c;}
function infer(d){const alpha=level(d.confidence),prop=d.method==='proportion',df=d.method==='t'?d.n-1:null;count(d.n,'n',prop?1:2);if(d.n>1e6)throw Error('n no debe superar 1 000 000 en inferencia.');if(!['z','t','proportion'].includes(d.method))throw Error('Método desconocido.');if(!['two','left','right'].includes(d.tail))throw Error('Selecciona una alternativa válida.');let estimate,se,seCI,warnings=[],formula,substitution,ci;
const critical=quantile(1-alpha/(d.tail==='two'?2:1),df),q=quantile(1-alpha/2,df);
if(prop){probability(d.nullValue,'p₀');count(d.success,'Éxitos',0);if(d.success>d.n)throw Error('Los éxitos no pueden superar n.');estimate=d.success/d.n;se=Math.sqrt(d.nullValue*(1-d.nullValue)/d.n);seCI=Math.sqrt(estimate*(1-estimate)/d.n);formula='Z = (p̂ − p₀) / √[p₀(1 − p₀)/n]';substitution=`(${estimate} − ${d.nullValue}) / √[${d.nullValue} × ${1-d.nullValue} / ${d.n}]`;if(d.n*d.nullValue<10||d.n*(1-d.nullValue)<10)warnings.push('La aproximación normal para esta prueba no es adecuada: n·p₀ y n·(1−p₀) deben ser al menos 10. Usa una prueba binomial exacta; la decisión Z se muestra solo como aproximación.');const z=quantile(1-alpha/2),den=1+z*z/d.n,center=(estimate+z*z/(2*d.n))/den,half=z*Math.sqrt(estimate*(1-estimate)/d.n+z*z/(4*d.n*d.n))/den;ci=[Math.max(0,center-half),Math.min(1,center+half)];
}else{valid(d.mean,'Media');valid(d.nullValue,'μ₀');positive(d.sd,d.method==='z'?'σ':'s');estimate=d.mean;se=d.sd/Math.sqrt(d.n);seCI=se;ci=[estimate-q*se,estimate+q*se];formula=`${d.method==='t'?'t':'Z'} = (x̄ − μ₀) / (${d.method==='t'?'s':'σ'} / √n)`;substitution=`(${d.mean} − ${d.nullValue}) / (${d.sd} / √${d.n})`;if(d.n<30)warnings.push('Muestra pequeña: comprueba que la población sea aproximadamente normal y que no existan valores atípicos importantes.');}
const statistic=(estimate-d.nullValue)/se,p=d.tail==='two'?2*sf(Math.abs(statistic),df):d.tail==='right'?sf(statistic,df):sf(-statistic,df);return {...d,alpha,df,estimate,se,seCI,ci,q,critical,statistic,p:Math.max(0,Math.min(1,p)),reject:p<=alpha,warnings,formula,substitution};}
function interval(d){const alpha=level(d.confidence);count(d.n,'n',d.method==='proportion'?1:2);if(d.n>1e6)throw Error('n no debe superar 1 000 000.');if(d.method==='proportion'){count(d.success,'Éxitos',0);if(d.success>d.n)throw Error('Los éxitos no pueden superar n.');const p=d.success/d.n,z=quantile(1-alpha/2),den=1+z*z/d.n,c=(p+z*z/(2*d.n))/den,h=z*Math.sqrt(p*(1-p)/d.n+z*z/(4*d.n*d.n))/den;return {estimate:p,ci:[Math.max(0,c-h),Math.min(1,c+h)],q:z,margin:h,center:c,method:'Wilson',formula:'Centro = (p̂ + z²/2n)/(1 + z²/n); semiancho = z·√[p̂(1−p̂)/n + z²/4n²]/(1 + z²/n)'};}if(!['t','z'].includes(d.method))throw Error('Método desconocido.');valid(d.mean,'Media');positive(d.sd,'Desviación');const q=quantile(1-alpha/2,d.method==='t'?d.n-1:null),margin=q*d.sd/Math.sqrt(d.n);return {estimate:d.mean,ci:[d.mean-margin,d.mean+margin],q,margin,center:d.mean,method:d.method==='t'?'t de Student':'Z',formula:'IC = x̄ ± valor crítico × desviación / √n'};}
function sample(d){const alpha=level(d.confidence);positive(d.error,'Margen de error');const z=quantile(1-alpha/2);let variance;if(d.parameter==='proportion'){probability(d.p,'Proporción prevista');if(d.error>=1)throw Error('El error de una proporción debe estar entre 0 y 1.');variance=d.p*(1-d.p);}else if(d.parameter==='mean'){positive(d.sd,'Desviación prevista');variance=d.sd*d.sd;}else throw Error('Parámetro desconocido.');const n0=z*z*variance/(d.error*d.error);if(!Number.isFinite(n0)||n0>1e12)throw Error('El tamaño calculado supera el rango admitido; revisa el error.');if(d.finite)count(d.population,'Población N',2);const exact=d.finite?n0/(1+(n0-1)/d.population):n0;return {z,n0,exact,n:Math.max(1,Math.ceil(exact)),formula:d.parameter==='proportion'?'n₀ = z² · p(1−p) / E²':'n₀ = z² · σ² / E²'};}
const api={lgamma,beta,valid,positive,count,probability,level,summary,infer,interval,sample,quantile,sf,density};if(typeof module!=='undefined')module.exports=api;root.Stats=api;
})(typeof globalThis!=='undefined'?globalThis:this);
